client_id = "a419293d1339cc23b5841538d18a1710"
name = "Pagnetic"
application_url = "https://pagnetic.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_products,read_customer_events,read_orders,write_app_proxy,write_pixels"

[app_proxy]
url = "/storefront/experience"
prefix = "apps"
subpath = "adaptive-storefront"

[auth]
redirect_urls = ["https://pagnetic.fly.dev/auth/callback"]

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"

[[webhooks.subscriptions]]
topics = ["orders/updated"]
uri = "/webhooks/orders/updated"

[[webhooks.subscriptions]]
topics = ["orders/cancelled"]
uri = "/webhooks/orders/cancelled"

[[webhooks.subscriptions]]
topics = ["refunds/create"]
uri = "/webhooks/refunds/create"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/webhooks/shop/redact"
